version: "3"
services:
  monzo:
    container_name: monzo
    build: .
    ports:
      - "36789:36789/tcp"
    environment:
      MONZO_REDIRECT_URI: ${MONZO_REDIRECT_URI}
      MONZO_CLIENT_ID: ${MONZO_CLIENT_ID}
      MONZO_CLIENT_SECRET: ${MONZO_CLIENT_SECRET}
      TRUE_LAYER_REDIRECT_URI: ${TRUE_LAYER_REDIRECT_URI}
      TRUE_LAYER_CLIENT_ID: ${TRUE_LAYER_CLIENT_ID}
      TRUE_LAYER_CLIENT_SECRET: ${TRUE_LAYER_CLIENT_SECRET}
    volumes:
      - './etc/monzo/:/etc/monzo/'
    restart: unless-stopped